version: '3.8'

services:
  diet-workout-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: diet-workout-recommendation-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - diet-workout-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  diet-workout-network:
    driver: bridge

volumes:
  logs: 