services:
  - type: web
    name: diet-workout-recommendation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x render-start.sh && ./render-start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 